apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservas-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservas-api
  template:
    metadata:
      labels:
        app: reservas-api
    spec:
      containers:
        - name: reservas-api
          image: reservas-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reservas-service
spec:
  type: NodePort
  selector:
    app: reservas-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
